services:
  - type: web
    name: whatsapp-sales-bot
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    # Persistent disk for SQLite database
    disk:
      name: whatsapp-bot-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:/opt/render/project/src/data/prod.db
      - key: OPENAI_API_KEY
        sync: false
      - key: ACCESS_TOKEN
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        sync: false
      - key: MY_PHONE_NUMBER
        sync: false
      - key: GABRIEL_PHONE
        sync: false
      - key: MIRIAM_PHONE
        sync: false
      - key: LETICIA_PHONE
        sync: false

